export const Loading = () => {
  return (
    <div className="flex w-full items-end justify-center">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        style={{ margin: "auto", background: "none" }}
        width="271"
        height="271"
        display="block"
        preserveAspectRatio="xMidYMid"
        viewBox="0 0 100 100"
      >
        <rect width="11" height="12" x="44.5" y="12" fill="#fe718d" rx="5.5" ry="6">
          <animate
            attributeName="opacity"
            begin="-0.9s"
            dur="1s"
            keyTimes="0;1"
            repeatCount="indefinite"
            values="1;0"
          ></animate>
        </rect>
        <rect
          width="11"
          height="12"
          x="44.5"
          y="12"
          fill="#f47e60"
          rx="5.5"
          ry="6"
          transform="rotate(36 50 50)"
        >
          <animate
            attributeName="opacity"
            begin="-0.8s"
            dur="1s"
            keyTimes="0;1"
            repeatCount="indefinite"
            values="1;0"
          ></animate>
        </rect>
        <rect
          width="11"
          height="12"
          x="44.5"
          y="12"
          fill="#f8b26a"
          rx="5.5"
          ry="6"
          transform="rotate(72 50 50)"
        >
          <animate
            attributeName="opacity"
            begin="-0.7s"
            dur="1s"
            keyTimes="0;1"
            repeatCount="indefinite"
            values="1;0"
          ></animate>
        </rect>
        <rect
          width="11"
          height="12"
          x="44.5"
          y="12"
          fill="#abbd81"
          rx="5.5"
          ry="6"
          transform="rotate(108 50 50)"
        >
          <animate
            attributeName="opacity"
            begin="-0.6s"
            dur="1s"
            keyTimes="0;1"
            repeatCount="indefinite"
            values="1;0"
          ></animate>
        </rect>
        <rect
          width="11"
          height="12"
          x="44.5"
          y="12"
          fill="#849b87"
          rx="5.5"
          ry="6"
          transform="rotate(144 50 50)"
        >
          <animate
            attributeName="opacity"
            begin="-0.5s"
            dur="1s"
            keyTimes="0;1"
            repeatCount="indefinite"
            values="1;0"
          ></animate>
        </rect>
        <rect
          width="11"
          height="12"
          x="44.5"
          y="12"
          fill="#6492ac"
          rx="5.5"
          ry="6"
          transform="rotate(180 50 50)"
        >
          <animate
            attributeName="opacity"
            begin="-0.4s"
            dur="1s"
            keyTimes="0;1"
            repeatCount="indefinite"
            values="1;0"
          ></animate>
        </rect>
        <rect
          width="11"
          height="12"
          x="44.5"
          y="12"
          fill="#637cb5"
          rx="5.5"
          ry="6"
          transform="rotate(216 50 50)"
        >
          <animate
            attributeName="opacity"
            begin="-0.3s"
            dur="1s"
            keyTimes="0;1"
            repeatCount="indefinite"
            values="1;0"
          ></animate>
        </rect>
        <rect
          width="11"
          height="12"
          x="44.5"
          y="12"
          fill="#6a63b6"
          rx="5.5"
          ry="6"
          transform="rotate(252 50 50)"
        >
          <animate
            attributeName="opacity"
            begin="-0.2s"
            dur="1s"
            keyTimes="0;1"
            repeatCount="indefinite"
            values="1;0"
          ></animate>
        </rect>
        <rect
          width="11"
          height="12"
          x="44.5"
          y="12"
          fill="#fe718d"
          rx="5.5"
          ry="6"
          transform="rotate(288 50 50)"
        >
          <animate
            attributeName="opacity"
            begin="-0.1s"
            dur="1s"
            keyTimes="0;1"
            repeatCount="indefinite"
            values="1;0"
          ></animate>
        </rect>
        <rect
          width="11"
          height="12"
          x="44.5"
          y="12"
          fill="#f47e60"
          rx="5.5"
          ry="6"
          transform="rotate(324 50 50)"
        >
          <animate
            attributeName="opacity"
            begin="0s"
            dur="1s"
            keyTimes="0;1"
            repeatCount="indefinite"
            values="1;0"
          ></animate>
        </rect>
      </svg>
    </div>
  );
};
